### ISSUE TITLE
Add support for authoring supplier(s)

### ISSUE THREAD

**Issue by janbiasi** [janbiasi/rollup-plugin-sbom#12]
According to [NTIA Minimum Elements](https://cyclonedx.org/guides/sbom/bom/) there should be a supplier or multiple suppliers listed in the BOM's metadata `bom.metadata.supplier`. ~~It would be a good idea to add an option to add the supplier via an option or infer the supplier via the "authors" field from `package.json`.~~

**Edit**: the plugin should not set any default value

**Comment by jkowalleck** [comment]
reminder: your tool is used by the manufacturer/author of the BOM, which is not necessarily the supplier of the BOM...

**Comment by janbiasi** [comment]
Thanks for the heads up @jkowalleck! I am aware that the author field does not necessarily contain the correct value. In your opinion, would it be better not to set a default value?

**Comment by jkowalleck** [comment]
> would it be better not to set a default value?

yes

**Comment by janbiasi** [comment]
> yes

Thanks a lot! I just updated the issue description to not use a default value at all.
